
env:
  system: Windows  # Linux or Windows to execute this project
  seed: 42
  name: WorkflowScheduling-v3
  traffic_pattern: CONSTANT
  gamma: 5  # Deadline factor for training process
  wf_size: S  # S, M, L, XL: the number of task in one workflow
  wf_num: 10  # The number of workflow in each training problem instance
  dataGen: 10000  # How many generations to iterate: the length of generative training dataset, usually >> generation for reproducible
  # evalNum: 1  # How many problem instances are used to evaluate each individual in training process, overwrite in base_config.py
  validNum: 3  # How many problem instances are used to verify the performance in testing process
  generateWay: rotation
  distributed_cloud_enabled: True

policy:
  name: model_workflow
  #  state_num: 8
  #  action_num: 1
  #  discrete_action: True
  add_gru: False
  action_type: greedy  # greedy or sampling

optim:
  name: es_openai
  population_size: 40
  maximization: True
  generation_num: 3000
  input_running_mean_std: True
  input_clip: False
  input_clip_value_min: Null
  input_clip_value_max: Null
  reward_shaping: True
  reward_norm: False
  sigma_init: 0.05  # noise standard deviation
  sigma_decay: 1.0
  learning_rate: 0.001
  learning_rate_decay: 0.9999
  reinforce_learning_rate: 0.001
  weight_decay: 0.0
